name: Security scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  sec_scan:
    runs-on: ubuntu-latest

  env:
    GITHUB_TOKEN: ${{ secrets.PRODSEC_SCANNER_READ_ONLY }}

  steps:

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: "go.mod"
        cache: false

    - name: "Configure GitHub PAT"
      run: |
        git config --global url."https://hashibot-prodsec:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"

    - name: Clone Security Scanner repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: hashicorp/security-scanner
        token: ${{ secrets.PRODSEC_SCANNER_READ_ONLY }}
        path: security-scanner
        ref: main


      
    - name: Scan
      id: scan
      uses: ./security-scanner
      with:
        repository: "$PWD" # (path or github.com/owner/name)
        config: |
          repository {
            go_modules = true
            osv        = true
            secrets {
              all = true
            } 
          }
          
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@f9a7c6738f28efb36e31d49c53a201a9c5d6a476 # codeql-bundle-v2.14.2
      with:
        sarif_file: results.sarif
