name: Security Scanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  sec_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Git
      env:
        GITHUB_TOKEN: ${{ secrets.HASHIBOT_PRODSEC_GITHUB_TOKEN }}
      run: |
        git config --global url."https://hashibot-prodsec:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Scan
      id: scan
      uses: hashicorp/security-scanner@main
      env:
        GITHUB_TOKEN: ${{ secrets.HASHIBOT_PRODSEC_GITHUB_TOKEN }}
      with:
        repository: "$PWD" # (path or github.com/owner/name)
        config: |
          repository {
            go_modules = true
            osv        = true
            secrets {
              all = true
            } 
          }

    - name: SARIF Output 
      shell: bash
      run: cat results.sarif | jq

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@f9a7c6738f28efb36e31d49c53a201a9c5d6a476 # codeql-bundle-v2.14.2
      with:
        sarif_file: results.sarif