name: Perform tests on unix and windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.21'

    - name: Test
      id: test
      run: |
        make test

    - name: Generate coverage comment
      id: gen_report
      run: |
        make test_coverage | tee report.txt

    - name: Generate coverage html report
      id: gen_html
      run: |    
        make test_coverage_html

    - name: Upload preview report to action run
      if: runner.os == 'Linux' && ${{ github.event.number != '' }}
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-coverage
        path: coverage.html

    - name: Write test coverage into PR comment
      if: runner.os == 'Linux' && ${{ github.event.number != '' }}
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '[Test coverage report generated](https://github.com/hashicorp/go-extract/actions/runs/${{ github.run_id }}) ✍

                  $(cat report.txt)'
          })
