name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: '1.21'

    - name: Test
      id: test
      run: |
        make test

  fuzzing:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: '1.21'

    - name: Test
      id: test
      run: |
        make fuzz

    - name: Get list of uncommitted files
      if: always()
      id: uncommitted
      shell: bash
      run: |
        uncommitted_files=$(git ls-files --others --exclude-standard)
        echo "::set-output name=stdout::$uncommitted_files"

    - name: upload all files from uncommitted list
      if: always()
      id: upload
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test_inputs_${{ runner.os }}
        path: |
          ${{ steps.uncommitted.outputs.stdout }}
      
